name: Formant
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
        persist-credentials: false
    - name: Prettify code
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{json,md}
        only_changed: True
        # Set your custom token
        github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}